#!/usr/bin/env bash
# 从 DustinWin games / games-cn 过滤 Steam 相关域名，合并补丁后生成 c-real-ip.yaml 与 c-real-ip-kw.list
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

GAMES_URL="${GAMES_URL:-https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/games.list}"
GAMES_CN_URL="${GAMES_CN_URL:-https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/games-cn.list}"
EXTRA_YAML="${EXTRA_YAML:-c-real-ip.extra.yaml}"
KW_BASE="${KW_BASE:-c-real-ip-kw.base.list}"
OUT_YAML="${OUT_YAML:-c-real-ip.yaml}"
OUT_KW="${OUT_KW:-c-real-ip-kw.list}"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

curl -fsSL "$GAMES_URL" -o "$tmpdir/games.list"
curl -fsSL "$GAMES_CN_URL" -o "$tmpdir/games-cn.list"

# 合并上游并筛出含 steam 的行（大小写不敏感）
grep -i steam "$tmpdir/games.list" "$tmpdir/games-cn.list" 2>/dev/null \
  | sed 's/^[^:]*://' \
  | sort -uf >"$tmpdir/steam-lines.txt" || true

suffix_file="$tmpdir/suffixes.txt"
plain_file="$tmpdir/plain-domains.txt"
: >"$suffix_file"
: >"$plain_file"

while IFS= read -r line || [[ -n "$line" ]]; do
  line="${line//$'\r'/}"
  [[ -z "$line" ]] && continue
  if [[ "$line" == +.* ]]; then
    echo "$line" >>"$suffix_file"
  elif [[ "$line" =~ ^[A-Za-z0-9.+-]+$ ]]; then
    echo "$line" >>"$plain_file"
  fi
done <"$tmpdir/steam-lines.txt"

# 合并 c-real-ip.extra.yaml 中的 +. 后缀
if [[ -f "$EXTRA_YAML" ]]; then
  grep -E '^[[:space:]]*-[[:space:]]*["'\'']?\+\.' "$EXTRA_YAML" \
    | sed -E 's/^[[:space:]]*-[[:space:]]*["'\'']?(\+\.[^"'\''[:space:]]+)["'\'']?.*/\1/' \
    >>"$suffix_file" || true
fi

sort -uf "$suffix_file" -o "$suffix_file"
sort -uf "$plain_file" -o "$plain_file"

suffix_count="$(wc -l <"$suffix_file" | tr -d ' ')"
plain_count="$(wc -l <"$plain_file" | tr -d ' ')"

{
  echo "# AUTO-GENERATED by scripts/sync-c-real-ip.sh — 请勿手改"
  echo "# 上游: $GAMES_URL"
  echo "#       $GAMES_CN_URL"
  echo "# 补丁: $EXTRA_YAML"
  echo "# 生成: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "payload:"
  while IFS= read -r suffix || [[ -n "$suffix" ]]; do
    echo "  - '$suffix'"
  done <"$suffix_file"
} >"$OUT_YAML"

{
  echo "# AUTO-GENERATED by scripts/sync-c-real-ip.sh — 请勿手改"
  if [[ -f "$KW_BASE" ]]; then
    grep -E '^[[:space:]]*DOMAIN(-SUFFIX|-KEYWORD|-REGEX)?,' "$KW_BASE" || true
  fi
  while IFS= read -r domain || [[ -n "$domain" ]]; do
    echo "DOMAIN-SUFFIX,$domain"
  done <"$plain_file"
} >"$OUT_KW"

kw_count="$(grep -cE '^DOMAIN' "$OUT_KW" || true)"
echo "sync-c-real-ip: $suffix_count suffix(es) -> $OUT_YAML, $plain_count plain + base -> $OUT_KW ($kw_count classical rule(s))"
