#!/usr/bin/env bash
# 从 Sukka ruleset.skk.moe 同步 download 规则，生成 c-download.yaml 与 c-download-kw.list
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DOWNLOAD_DOMAINSET_URL="${DOWNLOAD_DOMAINSET_URL:-https://ruleset.skk.moe/Clash/domainset/download.txt}"
DOWNLOAD_NON_IP_URL="${DOWNLOAD_NON_IP_URL:-https://ruleset.skk.moe/Clash/non_ip/download.txt}"
OUT_YAML="${OUT_YAML:-c-download.yaml}"
OUT_KW="${OUT_KW:-c-download-kw.list}"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

curl -fsSL "$DOWNLOAD_DOMAINSET_URL" -o "$tmpdir/download.txt"
curl -fsSL "$DOWNLOAD_NON_IP_URL" -o "$tmpdir/download-non-ip.txt"

suffix_file="$tmpdir/suffixes.txt"
: >"$suffix_file"

while IFS= read -r line || [[ -n "$line" ]]; do
  line="${line//$'\r'/}"
  [[ -z "$line" ]] && continue
  [[ "$line" =~ ^# ]] && continue
  [[ "$line" == *EOF* ]] && continue
  [[ "$line" =~ mad3_by_5ukk4w ]] && continue
  if [[ "$line" == +.* ]]; then
    echo "$line" >>"$suffix_file"
  elif [[ "$line" =~ ^[A-Za-z0-9.+-]+$ ]]; then
    echo "+.$line" >>"$suffix_file"
  fi
done <"$tmpdir/download.txt"

sort -uf "$suffix_file" -o "$suffix_file"
suffix_count="$(wc -l <"$suffix_file" | tr -d ' ')"

{
  echo "# AUTO-GENERATED by scripts/sync-sukka-download.sh — 请勿手改"
  echo "# 上游: $DOWNLOAD_DOMAINSET_URL"
  echo "# 生成: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "payload:"
  while IFS= read -r suffix || [[ -n "$suffix" ]]; do
    echo "  - '$suffix'"
  done <"$suffix_file"
} >"$OUT_YAML"

{
  echo "# AUTO-GENERATED by scripts/sync-sukka-download.sh — 请勿手改"
  echo "# 上游: $DOWNLOAD_NON_IP_URL"
  grep -E '^[[:space:]]*DOMAIN(-SUFFIX|-KEYWORD|-REGEX|-WILDCARD)?,' "$tmpdir/download-non-ip.txt" || true
} >"$OUT_KW"

kw_count="$(grep -cE '^DOMAIN' "$OUT_KW" || true)"
echo "sync-sukka-download: $suffix_count suffix(es) -> $OUT_YAML, $kw_count classical rule(s) -> $OUT_KW"
