#!/usr/bin/env bash
# 从 DustinWin games-cn 合并补丁，生成 games-cn.yaml
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

GAMES_CN_URL="${GAMES_CN_URL:-https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/games-cn.list}"
EXTRA_YAML="${EXTRA_YAML:-games-cn.extra.yaml}"
OUT_YAML="${OUT_YAML:-games-cn.yaml}"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

curl -fsSL "$GAMES_CN_URL" -o "$tmpdir/games-cn.list"

suffix_file="$tmpdir/suffixes.txt"
: >"$suffix_file"

while IFS= read -r line || [[ -n "$line" ]]; do
  line="${line//$'\r'/}"
  [[ -z "$line" ]] && continue
  [[ "$line" =~ ^# ]] && continue
  if [[ "$line" == +.* ]]; then
    echo "$line" >>"$suffix_file"
  elif [[ "$line" =~ ^[A-Za-z0-9.+-]+$ ]]; then
    echo "+.$line" >>"$suffix_file"
  fi
done <"$tmpdir/games-cn.list"

if [[ -f "$EXTRA_YAML" ]]; then
  grep -E '^[[:space:]]*-[[:space:]]*["'\'']?\+\.' "$EXTRA_YAML" \
    | sed -E 's/^[[:space:]]*-[[:space:]]*["'\'']?(\+\.[^"'\''[:space:]]+)["'\'']?.*/\1/' \
    >>"$suffix_file" || true
fi

sort -uf "$suffix_file" -o "$suffix_file"
suffix_count="$(wc -l <"$suffix_file" | tr -d ' ')"

{
  echo "# AUTO-GENERATED by scripts/sync-games-cn.sh — 请勿手改"
  echo "# 上游: $GAMES_CN_URL"
  echo "# 补丁: $EXTRA_YAML"
  echo "# 生成: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "payload:"
  while IFS= read -r suffix || [[ -n "$suffix" ]]; do
    echo "  - '$suffix'"
  done <"$suffix_file"
} >"$OUT_YAML"

echo "sync-games-cn: $suffix_count suffix(es) -> $OUT_YAML"
